services:
  - type: web
    name: netabot-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: RUNPOD_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
